platform: systemmonitor
resources:
  - type: processor_use
  - type: last_boot
  - type: processor_use
  - type: processor_temperature
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: throughput_network_in
    arg: eth0
  - type: throughput_network_out
    arg: eth0
  - type: packets_in
    arg: eth0
  - type: packets_out
    arg: eth0
  - type: ipv4_address
    arg: eth0
  - type: ipv6_address
    arg: eth0
  - type: disk_use_percent
    arg: /config
  - type: disk_use
    arg: /config
  - type: disk_free
    arg: /config
  - type: load_1m		
  - type: load_5m		
  - type: load_15m
  - type: memory_use_percent
  - type: memory_use
  - type: memory_free
  - type: swap_use_percent
  - type: swap_use
  - type: swap_free