- platform: influxdb
  name: "Default"
  host: [host]
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

- platform: influxdb
  name: "Glances"
  host: [host]
  port: 8086
  database: glances
  username: glances
  password: !secret glances_password
  max_retries: 3
  default_measurement: state