# GitHub Integration

sensor:
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'twhite96/SuburbanSmarts'
        name: Suburban Smarts
      - path: 'twhite96/js-dev-reads'
        name: JS Dev Reads
      - path: 'twhite/portfolio-v5'
        name: Portfolio