- id: '1632293006780'
  alias: Done Work
  description: ''
  trigger:
  - device_id: 8917568565f71c0086aa5ba970fb74e5
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: e77e08a0-19d4-4cde-bf98-b609425895ee
  condition: []
  action:
  - scene: scene.night_night
  mode: single
- id: '1632293365579'
  alias: Start Work
  description: ''
  trigger:
  - device_id: 8917568565f71c0086aa5ba970fb74e5
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 8ffc1b33-6789-4407-ad8c-0a24596967ad
  condition: []
  action:
  - scene: scene.get_ta_work
  mode: single
- id: '1634509305214'
  alias: Office lights activate
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: cf5ec4ba963a9edc92a39be28d5a3651
    entity_id: binary_sensor.office_motion_sensor_motion
    domain: binary_sensor
    id: '0001'
  condition:
  - condition: trigger
    id: '0001'
  - condition: time
    after: '12:00:00'
  - condition: and
    conditions:
    - type: is_illuminance
      condition: device
      device_id: cf5ec4ba963a9edc92a39be28d5a3651
      entity_id: sensor.office_motion_sensor_light_level
      domain: sensor
      below: 5
      above: 0
  action:
  - scene: scene.entering_office
  mode: single
- id: '1640714626821'
  alias: Turn on living room lights
  description: Turn on living room lights with the dimmer switch
  trigger:
  - device_id: e014e823f9e88d4078774a98b28f6927
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 18bc2c7f-1d67-4a36-b653-b99e344cd139
    id: '0004'
  condition: []
  action:
  - scene: scene.turn_on_living_room_lights_2
  mode: single
- id: '1640714857315'
  alias: Turn off living room lights at bedtime
  description: ''
  trigger:
  - device_id: e014e823f9e88d4078774a98b28f6927
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: 10c7381f-280d-4822-80bb-20aaf30ddefb
    id: '0004'
  condition: []
  action:
  - scene: scene.turn_off_living_room_lights_at_night
  mode: single
- id: '1640727292742'
  alias: Master Bathroom motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.master_bath_sensor_motion
      light_target:
        area_id: master_bathroom
      no_motion_wait: 325
- id: '1640727604990'
  alias: Test
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: automation.master_bathroom_motion
      target_entity: light.master_bathroom
      illuminance_sensor: sensor.master_bath_sensor_light_level
- id: '1641424296962'
  alias: Evening porch light on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition: []
  action:
  - type: turn_on
    device_id: b1172ed09c11ec17ba3a0213b36f470f
    entity_id: light.hue_white_lamp_1_3
    domain: light
    flash: long
  - condition: state
    entity_id: light.hue_white_lamp_1_3
    attribute: brightness
    state: 60%
  mode: single
- id: '1641424581151'
  alias: Porch light off in the morning
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
    id: '0007'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: weather.openweathermap
      attribute: forecast
      state: cloudy
  action:
  - type: turn_off
    device_id: 4bf8c0bc4848f582a11ebdbaafe7498d
    entity_id: light.light
    domain: light
  mode: single
- id: '1641428035171'
  alias: Kitchen lights on
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.master_bath_sensor_motion
      light_target:
        entity_id:
        - light.kitchen
      no_motion_wait: 500
- id: '1642840892073'
  alias: Switch bedroom lights on
  description: ''
  trigger:
  - device_id: 73d43f030cd64813e19b99aecd5514d8
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 96cc1fc4-c1e4-40ad-985c-743bf64f64a4
    id: '0010'
  condition: []
  action:
  - scene: scene.switch_bedroom_lights_on
  mode: single
- id: '1642840987513'
  alias: Switch bedroom lights off
  description: ''
  trigger:
  - device_id: 73d43f030cd64813e19b99aecd5514d8
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: 20b45320-c95e-47d7-bc65-8b2ffd33ac27
    id: '0011'
  condition: []
  action:
  - scene: scene.switch_bedroom_lights_off
  mode: single
- id: '1643143620307'
  alias: Flip the office lights on
  description: ''
  trigger:
  - device_id: 8917568565f71c0086aa5ba970fb74e5
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 8ffc1b33-6789-4407-ad8c-0a24596967ad
    id: '0012'
  condition: []
  action:
  - scene: scene.flip_on_office_lights
  mode: single
- id: '1643143677971'
  alias: Flip off the office lights
  description: ''
  trigger:
  - device_id: 8917568565f71c0086aa5ba970fb74e5
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: e77e08a0-19d4-4cde-bf98-b609425895ee
    id: '0013'
  condition: []
  action:
  - scene: scene.flip_the_office_lights_off
  mode: single
- id: '1644639631154'
  alias: Why are you here?
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_ringing_sensor
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.nesthubmaxbad9
      message: 'God, someone is here. '
      language: en-US
  mode: single
- id: '1652072097261'
  alias: Kitchen Motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hue_motion_sensor_1_motion
      light_target:
        entity_id: light.kitchen
- id: '1653521558427'
  alias: Door's Open
  description: ''
  use_blueprint:
    path: rokam/tts-door-opening.yaml
    input:
      door_sensor: binary_sensor.front_door
      persons: person.t_home
      target: media_player.nesthubmaxbad9
      message-single: <person> Door is open. Please check to see who is there.
      message-multiple: <persons> please see who is at the door.
- id: '00008'
  alias: Porch on if cloudy
  description: 'Is it cloudy or rainy? Turn on the porch light'
  trigger:
  - platform: state
    entity_id: weather.openweathermap
    to:
      - "hail"
      - "lightning"
      - "cloudy"
      - "lightning-rainy"
      - "pouring"
      - "rainy"
      - "snowy"
      - "snowy-rainy"
  condition: []
  action:
  - service: light.turn_on
    target:
        entity_id: light.porch
    data:
        brightness: 255
        kelvin: 2700
- id: '0009'
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      data:
        entity_id: light.porch
