# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Example configuration.yaml entry
zeroconf:
# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    #base_url: http://192.168.0.10:8123
    service_name: google_say

# YAML configs
# homeassistant:
#   packages: !include_dir_merge_named packages/
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensor: !include_dir_merge_named sensors
switch: !include_dir_merge_named switches



# sensors: !include sensors.yaml
frontend:
  themes: !include_dir_merge_named themes
  # covers: !include_dir_merge_named covers
  extra_module_url:
  - /local/community/custom-brand-icons/custom-brand-icons.js


#################################################################
#                                                               #
#                        SSL/Server Config                      #
#                                                               #
#################################################################



http:
  # server_port: 8123
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  ip_ban_enabled: false
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  login_attempts_threshold: 5

#################################################################
#                                                               #
#                        Groups                                 #
#                                                               #
#################################################################

group: !include_dir_merge_named groups
light: !include light_groups.yaml

# Example configuration.yaml entry
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console (not Cloud Project ID!)
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id


# Nintendo Wishlist
nintendo_wishlist:
  country: US
  wishlist:
    - "STAR WARS™: Knights of the Old Republic™"
    - "ASSASSIN’S CREED® THE EZIO COLLECTION"
    - "The Elder Scrolls V: Skyrim"
    - "Assassins Creed: The Rebel Collection"
    - "The Legend of Zelda: Tears of the Kingdom"
  scan_interval:
    days: 0
    hours: 0
    minutes: 3
    seconds: 30
    milliseconds: 0

# Prescence detection
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      rick: 192.168.68.84
  - platform: bluetooth_le_tracker
    consider_home: 60
    new_device_defaults:
      track_new_devices: true

