# Example configuration.yaml entry
# group:
#   light:
#     name: Office
#     entities:
#       - light.desk_lamp
#       - light.desk_strip
#       - light.left_bar
#       - light.right_bar
#       - light.bookshelf_light_2
#       - light.office_shelf_1
#       - light.office_shelf_2
#   climate:
#     name: Climate
#     entities:
#       - sensor.netatmo_office_temperature
#       - sensor.netatmo_office_humidity