- id: '1632292690973'
  name: Night Night
  entities:
    light.office_lights:
      min_mireds: 111
      max_mireds: 556
      supported_color_modes:
      - color_temp
      - hs
      - xy
      color_mode: hs
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      entity_id:
      - light.desk_strip
      - light.monitor_bars
      - light.office_shelf_1
      - light.office_shelf_2
      - light.office
      - light.desk_lamp
      icon: mdi:lightbulb-group
      friendly_name: Office lights
      supported_features: 40
      state: 'on'
  icon: fas:moon
- id: '1632293306146'
  name: Get Ta Work
  entities:
    light.office_lights:
      min_mireds: 111
      max_mireds: 556
      supported_color_modes:
      - color_temp
      - hs
      - xy
      color_mode: color_temp
      brightness: 255
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      entity_id:
      - light.desk_strip
      - light.monitor_bars
      - light.office_shelf_1
      - light.office_shelf_2
      - light.office
      - light.desk_lamp
      icon: mdi:lightbulb-group
      friendly_name: Office lights
      supported_features: 40
      state: 'on'
  icon: fas:building
- id: '1634508877139'
  name: Entering Office
  entities:
    light.bookshelf_light_2:
      min_mireds: 111
      max_mireds: 666
      effect_list:
      - effect_colorloop
      - effect_pulse
      - effect_stop
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      color_temp: 276
      hs_color:
      - 27.059
      - 42.165
      rgb_color:
      - 255
      - 195
      - 147
      xy_color:
      - 0.446
      - 0.371
      icon: phu:floor-lamp
      friendly_name: Office Main
      supported_features: 55
      state: 'on'
    light.office_shelf_2:
      min_mireds: 154
      max_mireds: 556
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      color_temp: 275
      attribution: Data provided by Wyze
      state: 'on'
      available: true
      device model: WLPA19C
      mac: 7C78B21C5B12
      IP: 192.168.68.121
      RSSI: '-35'
      SSID: GetYourOwnWiFi
      icon: phu:bulbs-classic
      friendly_name: Office 1
      supported_features: 19
    light.office_shelf_1:
      min_mireds: 154
      max_mireds: 556
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      color_temp: 273
      attribution: Data provided by Wyze
      state: 'on'
      available: true
      device model: WLPA19C
      mac: 7C78B216CB1F
      IP: 192.168.68.116
      RSSI: '-33'
      SSID: GetYourOwnWiFi
      icon: phu:bulbs-classic
      friendly_name: Office 2
      supported_features: 19
    light.desk_lamp:
      min_mireds: 153
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 255
      color_temp: 230
      hs_color:
      - 26.722
      - 28.925
      rgb_color:
      - 255
      - 214
      - 181
      xy_color:
      - 0.401
      - 0.359
      mode: normal
      dynamics: none
      icon: phu:desk-lamp
      friendly_name: Desk lamp
      supported_features: 40
      state: 'on'
    light.desk_strip:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 255
      color_temp: 281
      hs_color:
      - 27.117
      - 43.528
      rgb_color:
      - 255
      - 194
      - 144
      xy_color:
      - 0.449
      - 0.373
      mode: normal
      dynamics: none
      icon: bha:led-strip
      friendly_name: Desk Strip
      supported_features: 40
      state: 'on'
    light.monitor_bars:
      min_mireds: 111
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      color_temp: 287
      rate_limit_total: 100
      rate_limit_remaining: 89
      rate_limit_reset_seconds: 6.763822078704834
      rate_limit_reset: 1641333628
      rate_limit_on: 5
      manufacturer: Govee
      model: H6056
      icon: hue:play-bar-v-two
      friendly_name: Monitor bars
      supported_features: 19
      state: 'on'
- id: '1640714538015'
  name: Turn on living room lights
  entities:
    light.living_room_lights:
      min_mireds: 111
      max_mireds: 666
      effect_list:
      - effect_colorloop
      - effect_pulse
      - effect_stop
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      color_temp: 319
      hs_color:
      - 27.618
      - 53.372
      rgb_color:
      - 255
      - 181
      - 118
      xy_color:
      - 0.485
      - 0.381
      entity_id:
      - light.couch_lamp
      - light.patio_door_lamp
      - light.living_room_strip
      icon: mdi:lightbulb-group
      friendly_name: Living room lights
      supported_features: 36
      state: 'on'
  icon: hue:dimmer-switch
- id: '1640714785233'
  name: Turn off living room lights at night
  entities:
    light.living_room_lights:
      min_mireds: 111
      max_mireds: 666
      effect_list:
      - effect_colorloop
      - effect_pulse
      - effect_stop
      supported_color_modes:
      - color_temp
      - hs
      entity_id:
      - light.couch_lamp
      - light.patio_door_lamp
      - light.living_room_strip
      icon: mdi:lightbulb-group
      friendly_name: Living room lights
      supported_features: 36
      state: 'off'
  icon: hue:dimmer-switch
- id: '1641427456650'
  name: Kitchen lights activate
  entities:
    light.kitchen:
      min_mireds: 153
      max_mireds: 454
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 255
      color_temp: 283
      hs_color:
      - 27.141
      - 44.062
      rgb_color:
      - 255
      - 193
      - 142
      xy_color:
      - 0.452
      - 0.373
      is_hue_group: true
      hue_scenes:
      - Bright
      - Energize
      - Savanna sunset
      - Nightlight
      - Read
      - Relax
      - Concentrate
      - Spring blossom
      - Arctic aurora
      - Tropical twilight
      - Dimmed
      hue_type: room
      lights:
      - Chandelier light 3
      - Chandelier light 2
      - Chandelier light 1
      - Kitchen down light
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Kitchen
      supported_features: 40
      state: 'on'
    scene.kitchen_tropical_twilight:
      group_name: Kitchen
      group_type: room
      name: Tropical twilight
      speed: 0.6388888888888888
      brightness: 43.7
      is_dynamic: true
      friendly_name: Kitchen Tropical twilight
      state: unknown
    scene.kitchen_dimmed:
      group_name: Kitchen
      group_type: room
      name: Dimmed
      speed: 0.5
      brightness: 30.31
      is_dynamic: false
      friendly_name: Kitchen Dimmed
      state: unknown
    scene.kitchen_arctic_aurora:
      group_name: Kitchen
      group_type: room
      name: Arctic aurora
      speed: 0.6388888888888888
      brightness: 30.71
      is_dynamic: true
      friendly_name: Kitchen Arctic aurora
      state: unknown
    scene.kitchen_savanna_sunset:
      group_name: Kitchen
      group_type: room
      name: Savanna sunset
      speed: 0.6190476190476191
      brightness: 80.71
      is_dynamic: true
      friendly_name: Kitchen Savanna sunset
      state: unknown
    scene.kitchen_nightlight:
      group_name: Kitchen
      group_type: room
      name: Nightlight
      speed: 0.5
      brightness: 0.39
      is_dynamic: false
      friendly_name: Kitchen Nightlight
      state: unknown
    scene.kitchen_read:
      group_name: Kitchen
      group_type: room
      name: Read
      speed: 0.5
      brightness: 100
      is_dynamic: false
      friendly_name: Kitchen Read
      state: unknown
    scene.kitchen_bright:
      group_name: Kitchen
      group_type: room
      name: Bright
      speed: 0.5
      brightness: 100
      is_dynamic: false
      friendly_name: Kitchen Bright
      state: unknown
    scene.kitchen_energize:
      group_name: Kitchen
      group_type: room
      name: Energize
      speed: 0.5
      brightness: 100
      is_dynamic: false
      friendly_name: Kitchen Energize
      state: unknown
    scene.kitchen_relax:
      group_name: Kitchen
      group_type: room
      name: Relax
      speed: 0.5
      brightness: 56.69
      is_dynamic: false
      friendly_name: Kitchen Relax
      state: unknown
    scene.kitchen_concentrate:
      group_name: Kitchen
      group_type: room
      name: Concentrate
      speed: 0.5
      brightness: 100
      is_dynamic: false
      friendly_name: Kitchen Concentrate
      state: unknown
    scene.kitchen_spring_blossom:
      group_name: Kitchen
      group_type: room
      name: Spring blossom
      speed: 0.5595238095238095
      brightness: 81.1
      is_dynamic: true
      friendly_name: Kitchen Spring blossom
      state: unknown
- id: '1642840700980'
  name: Switch bedroom lights off
  entities:
    light.bedroom_lights:
      min_mireds: 111
      max_mireds: 666
      effect_list:
      - effect_colorloop
      - effect_pulse
      - effect_stop
      supported_color_modes:
      - color_temp
      - hs
      entity_id:
      - light.bed_tv_strip
      - light.bedroom_light
      - light.glass_lamp
      icon: mdi:lightbulb-group
      friendly_name: Bedroom lights
      supported_features: 44
      state: 'off'
  icon: hue:dimmer-switch
- id: '1642840743828'
  name: Switch bedroom lights on
  entities:
    light.bedroom_lights:
      min_mireds: 111
      max_mireds: 666
      effect_list:
      - effect_colorloop
      - effect_pulse
      - effect_stop
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 207
      color_temp: 246
      hs_color:
      - 26.785
      - 33.706
      rgb_color:
      - 255
      - 207
      - 169
      xy_color:
      - 0.416
      - 0.363
      entity_id:
      - light.bed_tv_strip
      - light.bedroom_light
      - light.glass_lamp
      icon: mdi:lightbulb-group
      friendly_name: Bedroom lights
      supported_features: 44
      state: 'on'
  icon: hue:dimmer-switch
- id: '1643141909315'
  name: Flip on Office lights
  entities:
    light.office_lights:
      min_mireds: 111
      max_mireds: 554
      supported_color_modes:
      - color_temp
      - hs
      - xy
      color_mode: color_temp
      brightness: 255
      color_temp: 258
      hs_color:
      - 26.877
      - 37.182
      rgb_color:
      - 255
      - 202
      - 160
      xy_color:
      - 0.428
      - 0.367
      entity_id:
      - light.desk_strip
      - light.monitor_bars
      - light.office_shelf_1
      - light.office_shelf_2
      - light.office
      - light.desk_lamp
      icon: mdi:lightbulb-group
      friendly_name: Office lights
      supported_features: 40
      state: 'on'
  icon: hue:dimmer-switch
- id: '1643143545126'
  name: Flip the office lights off
  entities:
    light.office_lights:
      min_mireds: 111
      max_mireds: 666
      effect_list:
      - effect_colorloop
      - effect_pulse
      - effect_stop
      supported_color_modes:
      - color_temp
      - hs
      - xy
      entity_id:
      - light.desk_strip
      - light.monitor_bars
      - light.office_shelf_1
      - light.office_shelf_2
      - light.office_main
      - light.desk_lamp
      icon: mdi:lightbulb-group
      friendly_name: Office lights
      supported_features: 44
      state: 'off'
  icon: hue:dimmer-switch
- id: '1656805433299'
  name: Porch Light On
  entities:
    light.porch:
      supported_color_modes:
      - brightness
      is_hue_group: true
      hue_scenes: []
      hue_type: room
      lights:
      - Porch light
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Porch
      supported_features: 40
      color_mode: brightness
      brightness: 255
      state: 'on'
    light.hue_white_lamp_1_3:
      effect_list:
      - None
      - candle
      supported_color_modes:
      - brightness
      mode: normal
      dynamics: none
      friendly_name: Porch light
      supported_features: 44
      color_mode: brightness
      brightness: 255
      effect: None
      state: 'on'
  icon: phu:wall-lantern
  metadata:
    light.hue_white_lamp_1_3:
      entity_only: false
    light.porch:
      entity_only: false
- id: '1656805526720'
  name: Porch light off
  entities:
    light.hue_white_lamp_1_3:
      effect_list:
      - None
      - candle
      supported_color_modes:
      - brightness
      mode: normal
      dynamics: none
      friendly_name: Porch light
      supported_features: 44
      state: 'off'
    light.porch:
      supported_color_modes:
      - brightness
      is_hue_group: true
      hue_scenes: []
      hue_type: room
      lights:
      - Porch light
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Porch
      supported_features: 40
      state: 'off'
  icon: phu:wall-econic-lantern-base
  metadata:
    light.hue_white_lamp_1_3:
      entity_only: false
    light.porch:
      entity_only: true
