title: TW Suburban Smarts

lovelace:
  resources:
    - url: /hacsfiles/github-flexi-card/github-flexi-card.js
      type: module
    - url: /local/mini-graph-card-bundle.js?v=0.10.0
      type: module
    - url: /hacsfiles/surveillance-card.js?v=0
      type: module


## Stats sidebar  
views:
   - title: Stats
     path: stats
     icon: far:chart-bar
     badges: []
     cards:
        - type: horizontal-stack
          cards:
            - type: entities
              entities:
                - entity: sensor.dwains_dashboard_latest_version
                - entity: update.home_assistant_core_update
                - entity: update.home_assistant_operating_system_update
                - entity: update.home_assistant_supervisor_update
                - entity: sensor.mac_mini_last_update_trigger
                - entity: update.unifi_network_application_update
              title: Updates
              state_color: true
        - hours_to_show: 24
          graph: line
          type: sensor
          detail: 1
          entity: sensor.tiffdev_battery_level_2
          icon: phu:apple-iphone
        - hours_to_show: 24
          graph: line
          type: sensor
          detail: 1
          entity: sensor.woz_battery_level
          icon: phu:apple-ipad-pro
        - type: logbook
          entities:
            - automation.evening_patio_light_on
            - automation.patio_light_off_in_the_morning
            - !secret home_address
            - binary_sensor.front_door_tamper_2
          title: Logs
        - show_name: true
          show_icon: true
          show_state: true
          type: glance
          entities:
            - entity: person.rick
            - entity: person.t_home
            - entity: person.uncle_jose
          title: Persons
        - type: entities
          entities:
            - entity: sensor.tiffdev_bssid
            - entity: sensor.tiffdev_ssid
            - entity: sensor.woz_bssid
            - entity: sensor.woz_ssid
            - entity: sensor.mac_mini_bssid
            - entity: sensor.mac_mini_ssid
          title: SSID Connections
          state_color: false
          show_header_toggle: true
        - hours_to_show: 23
          graph: line
          type: sensor
          entity: sensor.mac_mini_storage
          detail: 2
        - type: entities
          entities:
            - entity: binary_sensor.mac_mini_camera_in_use
            - entity: binary_sensor.mac_mini_microphone_in_use
            - entity: sensor.mac_mini_active_camera
            - entity: sensor.mac_mini_displays
            - entity: sensor.mac_mini_primary_display_id
            - entity: sensor.mac_mini_active_microphone
            - entity: sensor.mac_mini_connection_type
            - entity: binary_sensor.mac_mini_active
          title: Mini Stats
          state_color: true
        - hours_to_show: 24
          graph: line
          type: sensor
          detail: 1
          entity: sensor.woz_storage
        - hours_to_show: 24
          graph: line
          type: sensor
          detail: 2
          entity: sensor.tiffdev_storage_2
        - chart_type: line
          period: hour
          days_to_show: 30
          type: statistics-graph
          entities:
            - >-
              sensor.netatmo_tiffany_s_place_weather_station_outdoor_module_temperature
          title: Weather Station Temp
          stat_types:
            - min
            - max
        - type: entities
          entities:
            - entity: sensor.twhite96_suburbansmarts_forks
            - entity: sensor.twhite96_suburbansmarts_discussions
            - entity: sensor.twhite96_suburbansmarts_issues
            - entity: sensor.twhite96_suburbansmarts_stars
          state_color: true
          show_header_toggle: true
          title: Suburban Smarts Stats
        - type: custom:github-flexi-card
        - chart_type: line
          period: hour
          days_to_show: 30
          type: statistics-graph
          entities:
            - sensor.netatmo_tiffany_s_place_weather_station_temperature
          stat_types:
            - min
            - max
          title: Indoor Temp
        - type: custom:uptime-card
          entity: switch.ss_docs_active
          title_adaptive_color: true
          status_adaptive_color: true
          icon_adaptive_color: true
          tooltip_adaptive_color: true
          bar:
            height: 31
            spacing: 5
            amount: 19
          init: {}
          color:
            ko: '#ff0000'
            half: '#ffa500'
            none: '#48566a'
          alias: {}
          tooltip: {}
          tap_action: {}
          blink:
            speed: 1
          clip: {}
        - hours_to_show: 24
          graph: line
          type: sensor
          entity: sensor.speedtest_download
          detail: 1
          theme: Light Soft UI Red
        - hours_to_show: 24
          graph: line
          type: sensor
          entity: sensor.speedtest_upload
          detail: 1
          theme: Light Soft UI Red
        - hours_to_show: 24
          graph: line
          type: sensor
          entity: sensor.speedtest_ping
          detail: 1
          theme: Light Soft UI Red
        - hours_to_show: 24
          graph: line
          type: sensor
          entity: !secret router
          detail: 2
          name: WAN Status
          icon: phu:google-wifi-router
        - hours_to_show: 24
          graph: line
          type: sensor
          detail: 2
          entity: !secret router
          name: Packets Sent
          icon: si:packer
          theme: Mushroom
        - type: entity
          entity: sensor.local_ip
          name: Local IP
          icon: phu:apple-iphone
          state_color: true
        - hours_to_show: 24
          graph: line
          type: sensor
          detail: 2
          entity: !secret router
          name: External IP
          icon: si:serverfault
        - type: custom:uptime-card
          icon_adaptive_color: true
          status_adaptive_color: true
          bar: {}
          tap_action: {}
          blink:
            speed: 3 
   # Analytics Dashboard         
   - title: Analytics
     path: analytics
     panel: false
     badges: []
     cards:
         - type: iframe
           url: >-
             https://plausible.io/share/tiffanywhite.dev?auth=y4EZgXWzd9aVN_smehW8W&theme=light&background=%23f4f1f7
           aspect_ratio: 100%
           title: Tiffany R. White Blog
         - type: iframe
           url: >-
             https://plausible.io/share/tiffanyrwhite.com?auth=yJCMXvxv0XWkADyHKWVEU&theme=light&background=%23f4f1f7
           aspect_ratio: 100%
           title: Portfolio
         - type: iframe
           aspect_ratio: 100%
           title: SS
           url: >-
             https://plausible.io/share/suburbansmarts.org?auth=1r0wsAFC2cyTO2-SzY9tR&theme=light&background=%23f4f1f7
         - type: iframe
           url: >-
             https://plausible.io/share/docs.suburbansmarts.org?auth=phW0RKgGfxvc-Rym0NYfK&theme=light&background=%23f4f1f7
           aspect_ratio: 100%
           title: Docs
         - type: iframe
           aspect_ratio: 100%
           url: >-
             https://plausible.io/share/failures.tiffanywhite.dev?auth=oel9DZyzu-ZQlrERTIvh9&theme=light&background=%23f4f1f7
           title: Fails
         - type: iframe
           url: >-
             https://plausible.io/share/tothecrazyones.org?auth=ab-E2h_mfdRtnIuP_I9DJ&theme=light&background=%232a213
           aspect_ratio: 100%
           title: The Crazy Ones
         - type: iframe
           url: >-
             https://plausible.io/share/tiffnotes.dev?auth=EXGfto5JMGH_RnzJXmEeJ&embed=true&theme=light&background=%23f4f1f7
           aspect_ratio: 100%
           title: tiff notes
 